---
title: "visualization part 1"
output: github_document
editor_options: 
  chunk_output_type: console
---
#总结：先用ggplot定义，然后在geom 去选择想要的图
```{r}
library(tidyverse)


knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

Get the data for plotting 
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2023-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10, 
    month = lubridate::floor_date(date, unit = "month"))|>
  select(name, id, everything())
```

## Initial numeric work

```{r}
 weather_df |>
  ggplot(aes(x = prcp)) +
  geom_histogram()
  
```

```{r}
weather_df|>
  filter(prcp > 1000)
```

```{r}
weather_df|>
  filter(tmax >= 20, tmax <= 30) |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point()
```

## Grouping 
```{r}
weather_df|>
  group_by(name)
```

## Counting

```{r}
weather_df|>
  group_by( month)|>
  summarize(n_obs = n())
```

```{r}
weather_df|>
  count(name, name = "n_obs")
```

```{r}
weather_df|>
  count(name, month)|>
  pivot_wider(
    names_from = name, 
    values_from = n
  )
```

## General summaries
```{r}
weather_df|>
  group_by(name, month)|>
  summarize(
    mean_tmax = mean(tmax, na.rm = FALSE),
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE)
  )
```

```{r}
weather_df|>
  group_by(name, month)|>
  summarise( mean_tmax = mean(tmax, na.rm = TRUE))|>
  ggplot(aes(x = month, y = mean_tmax, color = name))+
  geom_point() + 
  geom_line()
```

```{r}
weather_df|>
  group_by(name, month)|>
  summarise( mean_tmax = mean(tmax, na.rm = TRUE))|>
  pivot_wider(
    names_from = name,
    values_from = mean_tmax
  )|>
  knitr::kable(digits = 2) #炫酷的图表
```

